name: GitOps Manifest Module

on:
  workflow_call:
    inputs:
      manifest-path:
        description: Path to the kubernetes file to update
        required: false
        type: string
        default: "k8s/api.yaml"
      egress-policy:
        description: Harden runner policy (audit or block)
        required: false
        type: string
        default: "audit"
      allowed-endpoints:
        description: Allowed endpoints when policy is block
        required: false
        type: string
        default: ""
    secrets:
      GITOPS_PAT:
        required: false

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920
        with:
          egress-policy: ${{ inputs.egress-policy }}
          allowed-endpoints: ${{ inputs.allowed-endpoints }}

      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: '1'
          token: '${{ secrets.GITOPS_PAT || github.token }}'

      - name: Update Deployment Image Tag
        env:
          REPO_NAME: ${{ github.repository }}
          SHORT_SHA: ${{ github.sha }}
          MANIFEST_PATH: ${{ inputs.manifest-path }}
        run: |
          REPO_LC=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]')
          SHORT_SHA=$(echo "$SHORT_SHA" | cut -c1-7)
          TAG="main-${SHORT_SHA}"
          IMAGE_NAME="ghcr.io/${REPO_LC}:${TAG}"

          echo "Updating Kubernetes deployment image to: ${IMAGE_NAME}"

          sed -i "s|image: ghcr.io/${REPO_LC}:.*|image: ${IMAGE_NAME}|g" "$MANIFEST_PATH"

      - name: Commit and Push Updated Manifests
        env:
          SHORT_SHA: ${{ github.sha }}
          MANIFEST_PATH: ${{ inputs.manifest-path }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "$MANIFEST_PATH"

          if git diff --staged --quiet; then
            echo "No manifest changes detected."
          else
            SHORT_SHA=$(echo "$SHORT_SHA" | cut -c1-7)
            git commit -m "chore(gitops): update image tag to main-${SHORT_SHA} [skip ci]"
            git push
          fi
